-- DDL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE redesocial;

USE redesocial;

CREATE TABLE redesocial (
	Id INT NOT NULL PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Foto VARCHAR(255) NULL,
);

CREATE TABLE redesocial (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Descricao VARCHAR(255) NOT NULL
);

CREATE TABLE tb_posts (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) NOT NULL,
	Descricao VARCHAR(255) NOT NULL,
	Foto VARCHAR(255) NULL,
	FK_Criar INT NOT NULL,
	FK_Temas INT NOT NULL,
	FOREIGN KEY (FK_Criar) REFERENCES redesocial (Id),
	FOREIGN KEY (FK_Temas) REFERENCES redesocial (Id)
);

CREATE TABLE tb_friends (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	id_amigo VARCHAR(255) NOT NULL,
	emComun VARCHAR(255) NOT NULL,
	Foto VARCHAR(255) NULL,
	FK_foloow INT NOT NULL,
	FK_likes INT NOT NULL,
	FOREIGN KEY (FK_foloow) REFERENCES redesocial (Id),
	FOREIGN KEY (FK_likes) REFERENCES redesocial (Id)
);

ALTER TABLE tb_usuarios ADD Cpf VARCHAR(50) NOT NULL;

ALTER TABLE tb_usuarios DROP COLUMN Cpf;

ALTER TABLE tb_usuarios ALTER COLUMN Foto VARCHAR(100) NOT NULL;

DROP TABLE tb_posts;

DROP DATABASE redesocial;